### ISSUE TITLE
I am getting an error message that I cannot debug

### ISSUE THREAD

**Issue by harmbuisman** [jmerle/lux-eye-2022#1]
Hi Jasper,

I cannot seem to run the attached json in the tool. The error message does not point me to the problem. 

I created the json locally using a similar approach as in your integration notebook on Kaggle.

Do you know what goes wrong?

Cannot load episode from run76.json
Cannot set properties of undefined (setting '0')

[run76.zip](https://github.com/jmerle/lux-eye-2022/files/10049281/run76.zip)

**Comment by jmerle** [comment]
Fixed in 281d5048c81b46cd8b7314a1ed20957975d0315a, thanks for reporting the issue!

**Comment by harmbuisman** [comment]
thanks, that was fast!
